version: "3"
services:
  redis: # 서비스 명
    image: redis:latest # 사용할 이미지
    container_name: redis # 컨테이너 이름
    restart: always # 서버 자동 재시작
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes: # 공유 저장소 설정
      - ./db/redis:/db
    command: redis-server
